project:
  type: book

book:

   title: "Data Science Looks at Discrimination"
   subtitle: "A toolkit for investigating bias in race, gender, age and so on"
   author: 
     - Norman Matloff, Project Lead
     - Taha Abdullah
     - Arjun Ashok
     - Shubhada Martha
     - Aditya Mittal 
     - Billy Ouattara 
     - Jonathan Tran
     - Brandon Zarate
   date: "9/16/2023"
   
   chapters:
     - index.qmd
     - intro.qmd
     - PartI.qmd
     - PartII.qmd
     - Appendices.qmd
   
format:
  pdf:
     toc: true
     number-sections: true
     fig_caption: no
     fig_numbers: no


